In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6517, 2623, 2629, 1690],
 [6517, 2623, 2629, 4582],
 [6517, 1558, 2629, 1429],
 [6544, 9492, 1842, 6112, 4316],
 [6544, 9492, 1842, 6112, 3510],
 [4729, 6517, 2732, 2629, 9776],
 [4746, 5647, 5482, 6112]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6517 2623 2629 1690]
 [   0    0    0    0 6517 2623 2629 4582]
 [   0    0    0    0 6517 1558 2629 1429]
 [   0    0    0 6544 9492 1842 6112 4316]
 [   0    0    0 6544 9492 1842 6112 3510]
 [   0    0    0 4729 6517 2732 2629 9776]
 [   0    0    0    0 4746 5647 5482 6112]]


In [10]:
## feature representation
dim=10

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model = Sequential([
    Embedding(
        input_dim=voc_size,
        output_dim=dim,
        input_shape=(sent_length,)
    )
])

model.compile(
    optimizer="adam",
    loss="mse"
)

c:\Users\Raaj\.conda\envs\ann\Lib\site-packages\keras\src\layers\core\embedding.py:126: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 226ms/step


array([[[-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.0339514 , -0.04410335,  0.04439243, -0.01221615,
          0.0197485 , -0.02488523,  0.00312531,  0.01186126,
          0.01577092,  0.0139345 ],
        [ 0.02805496, -0.0087172 ,  0.02139295,  0.02155607,
          0.02729067, -0.04045356,  0.03533352, -0.02268802,
         -0.0293469 , -0.01247688],
        [ 0.00305695, -0.04680241,  0.03425446, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 6517, 2623, 2629, 1690], dtype=int32)

In [21]:
import numpy as np

sample = np.array([embedded_docs[0]])
model.predict(sample)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step


array([[[-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.02934663, -0.04379496, -0.0367103 ,  0.03745636,
          0.04862412,  0.04831374,  0.00727048, -0.01927635,
          0.00014133, -0.00079232],
        [-0.0339514 , -0.04410335,  0.04439243, -0.01221615,
          0.0197485 , -0.02488523,  0.00312531,  0.01186126,
          0.01577092,  0.0139345 ],
        [ 0.02805496, -0.0087172 ,  0.02139295,  0.02155607,
          0.02729067, -0.04045356,  0.03533352, -0.02268802,
         -0.0293469 , -0.01247688],
        [ 0.00305695, -0.04680241,  0.03425446, -0.0